CREATE TABLE `t_api_release` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'API唯一编号',
    `name` varchar(64) NOT NULL COMMENT 'API名称，同一集群内唯一',
    `description` varchar(256) NOT NULL DEFAULT '' COMMENT 'API描述',
    `cluster_code` varchar(64) NOT NULL COMMENT '所属集群编码',
    `protocol` varchar(32) NOT NULL COMMENT '协议，例：HTTP',
    `path` varchar(150) NOT NULL COMMENT '请求路径',
    `method` varchar(32) NOT NULL DEFAULT '' COMMENT 'http请求方法',
    `param_trans_type` varchar(32) NOT NULL DEFAULT '' COMMENT '入参传递模式',
    `param_trans_config` mediumtext COMMENT '入参传递配置',
    `create_user` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人用户id',
    `update_user` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人用户id',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `version` int(11) NOT NULL DEFAULT '1' COMMENT '数据版本号',
    `lock_type` varchar(32) NOT NULL DEFAULT '' COMMENT '乐观锁：操作类型',
    `status` varchar(32) NOT NULL COMMENT '状态',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_clusterCode_path_method` (`cluster_code`, `path`, `method`),
    UNIQUE INDEX `uk_clusterCode_name` (`cluster_code`, `name`),
    KEY `idx_name` (`name`(20)),
    KEY `idx_path` (`path`(20)),
    KEY `idx_create_user` (`create_user`(20)),
    KEY `idx_update_user` (`update_user`(20)),
    KEY `idx_status` (`status`(20)),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='api inbound 配置表';


CREATE TABLE `t_api_draft` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `api_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 't_api_release.id',
    `name` varchar(64) NOT NULL COMMENT 'API名称，同一集群内唯一',
    `description` varchar(256) NOT NULL DEFAULT '' COMMENT 'API描述',
    `cluster_code` varchar(64) NOT NULL COMMENT '所属集群编码',
    `protocol` varchar(32) NOT NULL COMMENT '协议，例：HTTP',
    `path` varchar(150) NOT NULL COMMENT '请求路径',
    `method` varchar(32) NOT NULL DEFAULT '' COMMENT 'http请求方法',
    `param_trans_type` varchar(32) NOT NULL DEFAULT '' COMMENT '入参传递模式',
    `param_trans_config` mediumtext COMMENT '入参传递映射配置',
    `create_user` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人用户id',
    `update_user` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人用户id',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除0否 1 删除',
    `version` int(11) NOT NULL DEFAULT '1' COMMENT '数据版本号',
    `operate_type` varchar(32) NOT NULL COMMENT '操作类型',
    `status` varchar(32) NOT NULL COMMENT '状态',
    `apply_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '审批申请ID，t_apply.id',
    PRIMARY KEY (`id`),
    KEY `idx_clusterCode` (`cluster_code`(20)),
    KEY `idx_name` (`name`(20)),
    KEY `idx_path` (`path`(20)),
    KEY `idx_create_user` (`create_user`(20)),
    KEY `idx_update_user` (`update_user`(20)),
    KEY `idx_status` (`status`(20)),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_is_deleted` (`is_deleted`),
    KEY `idx_apply_id` (`apply_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='api inbound 配置变更表';


CREATE TABLE `t_out_service_release` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `api_release_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 't_api_release.id',
    `cluster_code` varchar(64) NOT NULL COMMENT '所属集群编码',
    `name` varchar(64) NOT NULL COMMENT '服务名称',
    `type` varchar(32) NOT NULL COMMENT '服务类型',
    `protocol` varchar(32) NOT NULL COMMENT '服务所用协议',
    `uri` varchar(1024) NOT NULL COMMENT '服务uri',
    `path` varchar(150) NOT NULL COMMENT '请求路径',
    `method` varchar(32) NOT NULL DEFAULT '' COMMENT 'http请求方法',
    `param_trans_type` varchar(32) NOT NULL DEFAULT '' COMMENT '入参传递模式',
    `param_trans_config` mediumtext COMMENT '入参传递映射配置',
    `response_trans_type` varchar(32) NOT NULL DEFAULT '' COMMENT '响应传递模式',
    `response_trans_config` mediumtext COMMENT '响应传递映射配置',
    `create_user` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人用户id',
    `update_user` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人用户id',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_clusterCode_apiReleaseId_name` (`cluster_code`, `api_release_id`, `name`),
    KEY `idx_clusterCode` (`cluster_code`(20)),
    KEY `idx_name` (`name`(20)),
    KEY `idx_path` (`path`(20)),
    KEY `idx_create_user` (`create_user`(20)),
    KEY `idx_update_user` (`update_user`(20)),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='api后端服务配置表';


CREATE TABLE `t_out_service_draft` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `api_draft_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 't_api_draft.id',
    `cluster_code` varchar(64) NOT NULL COMMENT '所属集群编码',
    `name` varchar(64) NOT NULL COMMENT '服务名称',
    `type` varchar(32) NOT NULL COMMENT '服务类型',
    `protocol` varchar(32) NOT NULL COMMENT '服务所用协议',
    `uri` varchar(1024) NOT NULL COMMENT '服务uri',
    `path` varchar(150) NOT NULL COMMENT '请求路径',
    `method` varchar(32) NOT NULL DEFAULT '' COMMENT 'http请求方法',
    `param_trans_type` varchar(32) NOT NULL DEFAULT '' COMMENT '入参传递模式',
    `param_trans_config` mediumtext COMMENT '入参传递映射配置',
    `response_trans_type` varchar(32) NOT NULL DEFAULT '' COMMENT '响应传递模式',
    `response_trans_config` mediumtext COMMENT '响应传递映射配置',
    `create_user` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人用户id',
    `update_user` varchar(64) NOT NULL DEFAULT '' COMMENT '修改人用户id',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_clusterCode_apiReleaseId_name` (`cluster_code`, `api_draft_id`, `name`),
    KEY `idx_clusterCode` (`cluster_code`(20)),
    KEY `idx_name` (`name`(20)),
    KEY `idx_path` (`path`(20)),
    KEY `idx_create_user` (`create_user`(20)),
    KEY `idx_update_user` (`update_user`(20)),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='api后端服务配置变更表';


CREATE TABLE `t_resource_lock` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `resource_type` varchar(64) NOT NULL COMMENT '资源类型',
    `resource_id` varchar(64) NOT NULL COMMENT '资源ID',
    `operation` varchar(64) NOT NULL DEFAULT '' COMMENT '操作说明',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_resourceType_resourceId` (`resource_type`, `resource_id`),
    KEY `idx_update_time` (`update_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源锁';