spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/janus?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: janus-admin

server:
  port: 8084

halo:
  influxdb:
    enable: true
    enableOkHttpClient: true
    url: 
    username: 
    password: 
    database: 
    retention-policy: autogen
    okhttp:
      connectTimeout: 10
  swagger:
    enabled: true
    api:
      title: janus-admin
      name: janus-admin
      description: Janus网关的管控平台
      version: 1.0.0
      contactName: jin.xu
      contactEmail: Software_King@qq.com
  mybatis:
    empty-where-intercept: false
  open-collection: false
  open-check: false
  web:
    corsEnabled: true
  shiro:
    apiUrl: /api/**
    loginUrl: /admin/login
    unauthorizedUrl: /403
    jwt-filter-url: /admin/**
    d-b-realm-enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/
  instance:
    prefer-ip-address: true

